HashMap<String, Object> countries = new HashMap<String, Object>();

boolean countryIsInString(String country, String searchResult) {
  return searchResult.contains(country);
}

void incrementCountryCountFromSearchResult(String searchResult) {
  for (String country : countries.keySet()) {
    if (countryIsInString("#"+country.toLowerCase(), searchResult.toLowerCase())) {
      println(country, searchResult);
    }
  }
}

void setupCountriesList() {
  countries.put("GRE", 0);
  countries.put("GHA", 0);
  countries.put("NGR", 0);
  countries.put("RSA", 0);
  countries.put("NED", 0);
  countries.put("NOR", 0);
  countries.put("NZL", 0);
  countries.put("DEN", 0);
  countries.put("GER", 0);
  countries.put("TLS", 0);
  countries.put("LAT", 0);
  countries.put("LBN", 0);
  countries.put("ROU", 0);
  countries.put("LUX", 0);
  countries.put("LTU", 0);
  countries.put("LIE", 0);
  countries.put("MAD", 0);
  countries.put("MAS", 0);
  countries.put("MEX", 0);
  countries.put("MON", 0);
  countries.put("MAR", 0);
  countries.put("MNE", 0);
  countries.put("MDA", 0);
  countries.put("MLT", 0);
  countries.put("MGL", 0);
  countries.put("USA", 0);
  countries.put("BER", 0);
  countries.put("BEL", 0);
  countries.put("BLR", 0);
  countries.put("BIH", 0);
  countries.put("BOL", 0);
  countries.put("BUL", 0);
  countries.put("BRA", 0);
  countries.put("SMR", 0);
  countries.put("SRB", 0);
  countries.put("SWE", 0);
  countries.put("SUI", 0);
  countries.put("ESP", 0);
  countries.put("SVK", 0);
  countries.put("SLO", 0);
  countries.put("SGP", 0);
  countries.put("ARM", 0);
  countries.put("ARG", 0);
  countries.put("ISL", 0);
  countries.put("IRL", 0);
  countries.put("AZE", 0);
  countries.put("AND", 0);
  countries.put("ALB", 0);
  countries.put("ERI", 0);
  countries.put("EST", 0);
  countries.put("ECU", 0);
  countries.put("GBR", 0);
  countries.put("AUS", 0);
  countries.put("AUT", 0);
  countries.put("OAR", 0);
  countries.put("UZB", 0);
  countries.put("UKR", 0);
  countries.put("IRI", 0);
  countries.put("ITA", 0);
  countries.put("ISR", 0);
  countries.put("IND", 0);
  countries.put("JPN", 0);
  countries.put("JAM", 0);
  countries.put("GEO", 0);
  countries.put("CHN", 0);
  countries.put("CZE", 0);
  countries.put("CHI", 0);
  countries.put("KAZ", 0);
  countries.put("CAN", 0);
  countries.put("KEN", 0);
  countries.put("KOS", 0);
  countries.put("COL", 0);
  countries.put("CRO", 0);
  countries.put("KGZ", 0);
  countries.put("CYP", 0);
  countries.put("TPE", 0);
  countries.put("THA", 0);
  countries.put("TUR", 0);
  countries.put("TOG", 0);
  countries.put("TGA", 0);
  countries.put("PAK", 0);
  countries.put("POR", 0);
  countries.put("POL", 0);
  countries.put("PUR", 0);
  countries.put("FRA", 0);
  countries.put("MKD", 0);
  countries.put("FIN", 0);
  countries.put("PHI", 0);
  countries.put("HUN", 0);
  countries.put("HKG", 0);
  countries.put("COR", 0);
}

// This is really not very helpful and should not be used
void setupCountriesListFull() {
  countries.put("Afghanistan", 0);
  countries.put("Georgia", 0);
  countries.put("Norway", 0);
  countries.put("Albania", 0);
  countries.put("Germany", 0);
  countries.put("Oman", 0);
  countries.put("Algeria", 0);
  countries.put("Ghana", 0);
  countries.put("Pakistan", 0);
  countries.put("American Samoa*", 0);
  countries.put("Greece", 0);
  countries.put("Palau", 0);
  countries.put("Andorra", 0);
  countries.put("Grenada", 0);
  countries.put("Palestine*", 0);
  countries.put("Angola", 0);
  countries.put("Guam", 0);
  countries.put("Panama", 0);
  countries.put("Antigua and Barbuda", 0);
  countries.put("Guatemala", 0);
  countries.put("Papua New Guinea", 0);
  countries.put("Argentina", 0);
  countries.put("Guinea", 0);
  countries.put("Paraguay", 0);
  countries.put("Armenia", 0);
  countries.put("Guinea-Bissau", 0);
  countries.put("Peru", 0);
  countries.put("Aruba", 0);
  countries.put("Guyana", 0);
  countries.put("Philippines", 0);
  countries.put("Australia", 0);
  countries.put("Haiti", 0);
  countries.put("Poland", 0);
  countries.put("Austria", 0);
  countries.put("Honduras", 0);
  countries.put("Portugal", 0);
  countries.put("Azerbaijan", 0);
  countries.put("Hong Kong", 0);
  countries.put("Puerto Rico", 0);
  countries.put("The Bahamas", 0);
  countries.put("Hungary", 0);
  countries.put("Qatar", 0);
  countries.put("Bahrain", 0);
  countries.put("Iceland", 0);
  countries.put("Romania", 0);
  countries.put("Bangladesh", 0);
  countries.put("India", 0);
  countries.put("Russian Federation", 0);
  countries.put("Barbados", 0);
  countries.put("Indonesia", 0);
  countries.put("Rwanda", 0);
  countries.put("Belarus", 0);
  countries.put("Iran", 0);
  countries.put("Saint Kitts", 0);
  countries.put("Nevis", 0);
  countries.put("Belgium", 0);
  countries.put("Iraq", 0);
  countries.put("Saint Lucia", 0);
  countries.put("Belize", 0);
  countries.put("Ireland", 0);
  countries.put("Saint Vincent", 0);
  countries.put("Grenadines", 0);
  countries.put("Bermuda", 0);
  countries.put("Israel", 0);
  countries.put("Samoa", 0);
  countries.put("Benin", 0);
  countries.put("Italy", 0);
  countries.put("San Marino", 0);
  countries.put("Bhutan", 0);
  countries.put("Jamaica", 0);
  countries.put("Sao Tome", 0);
  countries.put("Principe", 0);
  countries.put("Bolivia", 0);
  countries.put("Japan", 0);
  countries.put("Saudi Arabia", 0);
  countries.put("Bosnia", 0);
  countries.put("Herzegovina", 0);
  countries.put("Jordan", 0);
  countries.put("Senegal", 0);
  countries.put("Botswana", 0);
  countries.put("Kazakhstan", 0);
  countries.put("Serbia", 0);
  countries.put("Brazil", 0);
  countries.put("Kenya", 0);
  countries.put("Seychelles", 0);
  countries.put("Kiribati", 0);
  countries.put("Sierra Leone", 0);
  countries.put("Brunei", 0);
  countries.put("Korea", 0);
  countries.put("Singapore", 0);
  countries.put("Bulgaria", 0);
  countries.put("Slovakia", 0);
  countries.put("Burkina Faso", 0);
  countries.put("Kosovo", 0);
  countries.put("Slovenia", 0);
  countries.put("Burundi", 0);
  countries.put("Kuwait", 0);
  countries.put("Solomon Islands", 0);
  countries.put("Cambodia", 0);
  countries.put("Kyrgyzstan", 0);
  countries.put("Somalia", 0);
  countries.put("Cameroon", 0);
  countries.put("Laos", 0);
  countries.put("South Africa", 0);
  countries.put("Canada", 0);
  countries.put("Latvia", 0);
  countries.put("South Sudan", 0);
  countries.put("Cape Verde", 0);
  countries.put("Lebanon", 0);
  countries.put("Spain", 0);
  countries.put("Cayman", 0);
  countries.put("Lesotho", 0);
  countries.put("Sri Lanka", 0);
  countries.put("Central African Republic", 0);
  countries.put("Liberia", 0);
  countries.put("Sudan", 0);
  countries.put("Chad", 0);
  countries.put("Libya", 0);
  countries.put("Suriname", 0);
  countries.put("Chile", 0);
  countries.put("Liechtenstein", 0);
  countries.put("Swaziland", 0);
  countries.put("China", 0);
  countries.put("Lithuania", 0);
  countries.put("Sweden", 0);
  countries.put("Colombia", 0);
  countries.put("Luxembourg", 0);
  countries.put("Switzerland", 0);
  countries.put("Comoros", 0);
  countries.put("Macedonia", 0);
  countries.put("Syria", 0);
  countries.put("Madagascar", 0);
  countries.put("Taiwan", 0);
  countries.put("Chinese Taipei", 0);
  countries.put("Congo", 0);
  countries.put("Malawi", 0);
  countries.put("Tajikistan", 0);
  countries.put("Cook Islands", 0);
  countries.put("Malaysia", 0);
  countries.put("Tanzania", 0);
  countries.put("Costa Rica", 0);
  countries.put("Maldives", 0);
  countries.put("Thailand", 0);
  countries.put("Cote d'Ivoire", 0);
  countries.put("Mali", 0);
  countries.put("Togo", 0);
  countries.put("Croatia", 0);
  countries.put("Malta", 0);
  countries.put("Tonga", 0);
  countries.put("Cuba", 0);
  countries.put("Marshall Islands", 0);
  countries.put("Trinidad", 0);
  countries.put("Tobago", 0);
  countries.put("Cyprus", 0);
  countries.put("Mauritania", 0);
  countries.put("Tunisia", 0);
  countries.put("Czech Republic", 0);
  countries.put("Mauritius", 0);
  countries.put("Turkey", 0);
  countries.put("Denmark", 0);
  countries.put("Mexico", 0);
  countries.put("Turkmenistan", 0);
  countries.put("Djibouti", 0);
  countries.put("Micronesia", 0);
  countries.put("Tuvalu", 0);
  countries.put("Dominica", 0);
  countries.put("Moldova", 0);
  countries.put("Uganda", 0);
  countries.put("Dominican Republic", 0);
  countries.put("Monaco", 0);
  countries.put("Ukraine", 0);
  countries.put("East Timor", 0);
  countries.put("Timor-Leste", 0);
  countries.put("Mongolia", 0);
  countries.put("United Arab Emirates", 0);
  countries.put("UAE", 0);
  countries.put("Ecuador", 0);
  countries.put("Morocco", 0);
  countries.put("United Kingdom", 0);
  countries.put("Britain", 0);
  countries.put("UK", 0);
  countries.put("England", 0);
  countries.put("Egypt", 0);
  countries.put("Montenegro", 0);
  countries.put("United States", 0);
  countries.put("El Salvador", 0);
  countries.put("Mozambique", 0);
  countries.put("Uruguay", 0);
  countries.put("Guinea", 0);
  countries.put("Myanmar", 0);
  countries.put("Burma", 0);
  countries.put("Uzbekistan", 0);
  countries.put("Eritrea", 0);
  countries.put("Namibia", 0);
  countries.put("Vanuatu", 0);
  countries.put("Estonia", 0);
  countries.put("Nauru", 0);
  countries.put("Venezuela", 0);
  countries.put("Ethiopia", 0);
  countries.put("Nepal", 0);
  countries.put("Vietnam", 0);
  countries.put("Fiji", 0);
  countries.put("Netherlands", 0);
  countries.put("Virgin Islands", 0);
  countries.put("Finland", 0);
  countries.put("New Zealand", 0);
  countries.put("Yemen", 0);
  countries.put("France", 0);
  countries.put("Nicaragua", 0);
  countries.put("Zambia", 0);
  countries.put("Gabon", 0);
  countries.put("Niger", 0);
  countries.put("Zimbabwe", 0);
  countries.put("The Gambia", 0);
  countries.put("Nigeria", 0);
}